### ISSUE TITLE
Error message shows up

### ISSUE THREAD

**Issue by windvane** [suurjaak/Skyperious#130]
Hi,

When starting Skyperious, an error message shows up. Please help with this issue. Thank you.
----------------------------------------
Error message:
An unexpected error has occurred:
Error: (unsupported locale setting)
See log for full details.
----------------------------------------
Log:
An unexpected error has occurred:

			Traceback (most recent call last):
			  File "wx\core.py", line 2217, in OnPreInit
			  File "skyperious\main.py", line 342, in InitLocale
			  File "locale.py", line 608, in setlocale
			locale.Error: unsupported locale setting

**Comment by suurjaak** [comment]
Can you tell me the version of your operating system, and which Skyperious release did you try?

**Comment by windvane** [comment]
OS: Win 7 x64
Skyperious: 5.6 x64
I've tried to reinstall the software, but it doesn't work.

**Comment by suurjaak** [comment]
Is your Windows perhaps fully non-English?

**Comment by windvane** [comment]
My Windows is Chinese traditional. Skyperious 5.6 worked well originally, and then some system files have probably  been changed by other software and caused this Skyperious issue.

**Comment by suurjaak** [comment]
Thank you, this gives me enough information to hopefully fix the issue.

**Comment by windvane** [comment]
Any updates about this issue?

**Comment by suurjaak** [comment]
Should be fixed now with the newly released version 5.7. Can you confirm? 

Sorry for sitting on this so long.

**Comment by windvane** [comment]
After upgrading, I still get the error message below. Since Skype will be retiring in May 2025, please give up to fix this issue. Thanks for being willing to solve my problem.

An unexpected error has occurred:

			Traceback (most recent call last):
			  File "skyperious\gui.py", line 4362, in on_change_range_date
			  File "skyperious\lib\controls.py", line 739, in SetValue
			  File "skyperious\lib\controls.py", line 751, in SetText
			  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
			  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
			  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
			  File "PyInstaller\loader\pyimod02_importers.py", line 419, in exec_module
			  File "_strptime.py", line 268, in <module>
			  File "_strptime.py", line 182, in __init__
			  File "_strptime.py", line 69, in __init__
			  File "_strptime.py", line 28, in _getlang
			  File "locale.py", line 591, in getlocale
			  File "locale.py", line 499, in _parse_localename
			ValueError: unknown locale: en-US

**Comment by suurjaak** [comment]
Fair enough, but if you don't mind, I would still like to figure out this issue, as the same can arise in other programs I make. 

From what I understand, the startup error no longer occurs, but this new error pops up when you open a chat in Skyperious? 

Could you open the Python console (menu Help -> Show Python console), and there execute one by one:

```python
import locale

print(locale.getlocale())

print(locale.getdefaultlocale())

locale.setlocale(locale.LC_ALL, "")
```

What does it print it to console? And after the last, does opening a chat work?

**Comment by windvane** [comment]
Yes, this new error pops up when I open a chat in Skyperious.

The results from the console are:
1. The same error pops up. (ValueError: unknown locale: en-US)
2. ('zh_TW', 'cp950')
3. 'Chinese (Traditional)_Taiwan.950'

And after the last, opening a chat works. However, this issue occurs again after restarting Skyperious.

**Comment by suurjaak** [comment]
Aha, thank you, this gives me enough information to (hopefully) fix it once and for all.

**Comment by suurjaak** [comment]
Should finally be fixed now with the newly released version 5.8. Can you confirm?

**Comment by windvane** [comment]
The default destination folder of Skyperious 5.8 for 64-bit and 32-bit is wrong. Please fix it.
My issue got fixed in version 5.8.
